aravis:
  device_id: null            # 传None默认选择第一个设备
  pixel_format: "BayerRG8"   # 参考 arv-tool-0.8 输出
  width: 640
  height: 640
  packet_size: 9000          # jumbo frame
  packet_delay: 1000
  exposure_us: 8000
  gain_db: 6.0
  auto_exposure: false
  auto_gain: false
  stream_buffer_count: 8

network:
  interface: "enP8p1s0"
  host_ip: "192.168.100.1"
  camera_ip: "192.168.100.10"
  mtu: 9000

notes:
  - "使用 arv-tool-0.8 gvcp discover 校验设备"
  - "若像素格式不是 BayerRG8，更新 pixel_format 并调整处理逻辑"
