aravis:
  # --------------------------------------------------------------------------- #
  # 设备选择 & 输出格式
  # --------------------------------------------------------------------------- #
  device_id: null                    # 连接哪台相机：null=自动选第一台在线设备；建议填序列号避免串线
  pixel_format: "BayerGB8"           # 图像像素格式：BayerGB8/BayerRG8/RGB8/BGR8/Mono8 等，需与软件解码一致
  width: 640                         # 输出宽度（像素），超出相机支持范围会被自动裁剪
  height: 640                        # 输出高度（像素），搭配 offset_x/offset_y 控制 ROI
  offset_x: 0                        # 取景窗口左上角 X 偏移（像素），0 表示不偏移
  offset_y: 0                        # 取景窗口左上角 Y 偏移（像素），0 表示不偏移
  binning: 1                         # 传感器像素合并：1=关闭；2=2x2 合并，提亮降噪但牺牲分辨率
  decimation: 1                      # 采样抽取：1=逐像素，2=隔行/隔列丢弃，可换取更高 FPS
  frame_rate: 50.0                   # 目标帧率（Hz），网络拥塞时可适当下调

  # --------------------------------------------------------------------------- #
  # 曝光 / 增益 / 白平衡
  # --------------------------------------------------------------------------- #
  exposure_us: 3500                  # 手动曝光时间（微秒），滚动快门情况下应小于帧周期
  exposure_auto: "Off"             # 自动曝光模式：Off/Once/Continuous
  auto_exposure: false               # 兼容旧逻辑（遗留字段），等价于 exposure_auto="Continuous"
  exposure_auto_min: 500            # 自动曝光下限（微秒），避免过曝
  exposure_auto_max: 8000            # 自动曝光上限（微秒），避免过暗
  exposure_auto_target: 0.4          # 自动曝光亮度目标 (0.0~1.0)，相当于直方图目标值
  gain_db: 4.0                       # 手动增益（dB），噪声随增益线性上升，建议越小越好
  gain_auto: "Off"                # 自动增益模式：Off/Once/Continuous
  auto_gain: false                   # 兼容旧逻辑（遗留字段），等价于 gain_auto="Continuous"
  gain_auto_min: 0.0                 # 自动增益下限（dB）
  gain_auto_max: 12.0                # 自动增益上限（dB），过大画面将颗粒化
  gamma: 1.0                         # Gamma 校正，1.0 表示禁用；适当调高可压暗部提升亮度
  balance_ratio_red: 1.0             # 手动白平衡：红通道系数
  balance_ratio_blue: 1.0            # 手动白平衡：蓝通道系数
  white_balance_auto: true           # 是否启用自动白平衡；慢速环境可关，灯光频繁变化时建议开

  # --------------------------------------------------------------------------- #
  # 触发 / IO 线路
  # --------------------------------------------------------------------------- #
  trigger_mode: "Off"                # 触发模式：Off=自由运行，On=依赖外部触发
  trigger_source: "Line0"            # 触发源：Line0/Software/FrequencyConverter 等
  trigger_selector: "FrameStart"     # 触发作用对象：FrameStart/AcquisitionStart 等
  trigger_activation: "RisingEdge"   # 触发沿：RisingEdge/FallingEdge
  line_selector: "Line0"             # 配置哪条物理线路
  line_mode: "Output"                # 线路模式：Input=作为触发输入，Output=输出准备信号
  line_inverter: false               # 是否翻转线路电平，true 时逻辑电平取反

  # --------------------------------------------------------------------------- #
  # GigE Vision 传输（GVSP/GVCP）
  # --------------------------------------------------------------------------- #
  gev_packet_size: 1500              # GVSP 包大小：1500=标准以太网；9000=jumbo frame，需链路全支持
  gev_packet_delay: 120000        # 包间隔（ns），适当增大可削峰填谷减少丢包
  gev_stream_channel_selector: 0     # 流通道编号，单机默认 0，多流时可改
  gev_gvsp_extended_id_mode: false   # 是否启用 GVSP 扩展 ID；多目标/多流时建议打开
  gev_heartbeat_timeout: 1000        # GVCP 心跳超时（ms），控制端无响应超过该值将断连
  stream_buffer_count: 24            # Aravis 预分配缓冲个数，提高带宽抖动容忍度
  stream_buffer_size: null           # 单个缓冲大小（字节），null 表示按 payload 自动估算
  stream_buffer_handling: "NewestOnly"  # 缓冲策略：OldestFirst/NewestFirst/NewestOnly
  stream_retransmission: true        # 是否启用数据重传（Aravis >=0.8 支持）
  stream_packet_resend_timeout_ms: 200    #传超时（ms），过小会导致频繁重试，过大则重传延迟

  # --------------------------------------------------------------------------- #
  # 诊断 & 调试
  # --------------------------------------------------------------------------- #
  chunk_enable: false                # 是否启用 Chunk 数据（在图像附带额外元信息）
  chunk_selectors: []                # 需要输出的 Chunk 名称，如 ["Timestamp", "LineStatusAll"]
  stats_log_interval: 1.0            # 采集统计打印周期（秒），0 表示不打印

network:
  interface: "enP8p1s0"              # 主机使用的物理网卡名，ip addr 可查看
  host_ip: "192.168.100.1"           # 主机静态 IP（需要自行通过 netplan/NetworkManager 配置）
  camera_ip: "192.168.100.10"        # 相机静态 IP，需与 host_ip 同网段
  mtu: 9000                          # 网卡 MTU，使用 jumbo frame 时设置为 9000，否则保持 1500
  rx_ring: 1024                      # ethtool -G RX 环形缓冲长度，越大越抗突发流量
  tx_ring: 1024                      # ethtool -G TX 环形缓冲长度，发送排队容量
  enable_gro: false                  # 是否启用 GRO（大包聚合），低延迟场景建议关闭
  enable_lro: false                  # 是否启用 LRO（仅限服务器网卡），可能引入延迟
  enable_ntuple: false               # 是否启用 ntuple 过滤，可按需加速多流
  rss: false                         # 是否启用接收侧多队列 (Receive Side Scaling)，多核分发

notes:
  - "先用 `arv-tool-0.8 gvcp discover` 验证相机在线状态"
  - "调整 MTU 前确认交换机/网卡都支持 jumbo frame，否则改回 1500"
  - "Aravis 特性名可能与厂商手册略有差异，参数不生效时对照原厂文档核实"
  - "滚动快门避免撕裂：降低曝光、适度调大 gev_packet_delay、确保重传开启并关注 stats_log_interval 输出"
